### ISSUE TITLE
CandlestickData has no values when requested via GetCandlestickData methods

### ISSUE THREAD

**Issue by JustAnotherMakerChannel** [FastFinTech/FFT.Oanda#17]
The CandlestickData record properties have no get or init accessors and as such the Open, High, Low and Close properties are always zero when new CandlestickData is instantiated.

Adding the init accessor to these 4 properties solves the issue.

I've basically signed up to github to raise this so apologies if there is a means for me to rectify it!

**Comment by truegoodwill** [comment]
Good catch, really appreciate you notifying me.
Yes, theoretically, you would be able to fix the code and push it back to me in a pull request.
Thanks again! And sorry for not seeing this until now.
