### ISSUE TITLE
AccountFinancingMode DAILY_INSTRUMENT value missing

### ISSUE THREAD

**Issue by squideyes** [FastFinTech/FFT.Oanda#18]
Hi!

I'm getting an error while parsing the AccountFinancingMode enumeration for a DailyFinancingTransaction because the DAILY_INSTRUMENT value is missing.  I'm not quite sure what the value means, but as soon as I get the info back from OANDA I'll be sure make a pull request with the updated code.

**Comment by truegoodwill** [comment]
Thank you. Awesome pull request. I'm not sure if removing the cancellation tokens from the async enumerators was a good idea, I'll have to take a careful look at that. Thanks again.

**Comment by traburi** [comment]
Hi … 

 

it was not my intention to remove the cancelation token, but in net8 the MoveNextAsync doesn’t take a token any longer.

Maybe the stream is still listening on the cancelation token from the initialisation, but I didnt check that

 

Uli

 

Von: True Goodwill ***@***.***> 
Gesendet: Tuesday, 19 March 2024 16:19
An: FastFinTech/FFT.Oanda ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [FastFinTech/FFT.Oanda] AccountFinancingMode DAILY_INSTRUMENT value missing (Issue #18)

 

Thank you. Awesome pull request. I'm not sure if removing the cancellation tokens from the async enumerators was a good idea, I'll have to take a careful look at that. Thanks again.
