### ISSUE TITLE
MarketOrderRequest, MissingParameterException, Missing 'order' parameter

### ISSUE THREAD

**Issue by kaf94** [FastFinTech/FFT.Oanda#2]
Hello,

When creating a new MarketOrderRequest

OandaApiClient oandaClient = new OandaApiClient(AccountType.Real, "myOandaKey");

MarketOrderRequest newMarketOrder = new MarketOrderRequest(TimeInForce.FOK, null, OrderTriggerCondition.DEFAULT, null, "CAD/JPY", OrderPositionFill.DEFAULT, null, null, null, null, null, 100, null);
            
Task sendOrder = oandaClient.CreateOrder("myOandaAccountID", newMarketOrder);

I'm receiving a "Missing 'order' parameter" exception (see below)
![Capture](https://user-images.githubusercontent.com/85368612/149836079-ffeb4dc9-cee8-4609-b7e7-4730224238cb.PNG)

**Comment by antonma** [comment]
I also looking for an example how set an order.
In the example above: is it sell or buy order ? 
I also think that the instrument string is wrong and this should be "CAD_JPY"

Unfortunately I also was not able to send any order successfully ...

**Comment by traburi** [comment]
Have a look on my pull requests ... you'll find a solution there

All the best
Uli

**Comment by truegoodwill** [comment]
Thank you everybody for your input here. 
Uli, I'm looking at your PR.
